# Generated by Django 4.0.4 on 2022-04-30 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('dept', models.CharField(choices=[('AIDS', 'aids'), ('CSIT', 'csit'), ('CSE', 'cse')], max_length=100)),
            ],
        ),
    ]
