# Generated by Django 4.0.4 on 2022-04-30 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dept',
            field=models.CharField(choices=[('CSIT', 'csit'), ('CSE', 'cse'), ('AIDS', 'aids')], max_length=100),
        ),
    ]
