# Generated by Django 4.0.4 on 2022-04-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epc', '0002_alter_employee_dept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='empid',
        ),
        migrations.AlterField(
            model_name='employee',
            name='dept',
            field=models.CharField(max_length=100),
        ),
    ]
