# Generated by Django 4.0.4 on 2022-04-30 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epc', '0003_remove_employee_empid_alter_employee_dept'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='dept',
            new_name='password',
        ),
    ]
